services:
  feedback:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app/service
      - /usr/src/app/service/node_modules
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:  pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 3s
      timeout: 4m
      retries: 5
    restart: always