import { MigrationInterface, QueryRunner } from 'typeorm';

export class StatusSchema1734799895350 implements MigrationInterface {
  name = 'StatusSchema1734799895350';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "status" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `INSERT INTO "status" (value) VALUES ('noted'), ('planned'), ('in_progress'), ('done')`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "status"`);
  }
}
